# Generated by Django 2.2.5 on 2021-04-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210424_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='accruacy',
            new_name='accuracy',
        ),
    ]
