# Generated by Django 2.2.5 on 2021-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210515_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='created',
            field=models.DateTimeField(default='2021-05-16 18:47:56.785708+00:00'),
        ),
        migrations.AlterField(
            model_name='bookedday',
            name='updated',
            field=models.DateTimeField(default='2021-05-16 18:47:56.785727+00:00'),
        ),
    ]
