# Generated by Django 2.2.5 on 2021-05-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20210517_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='created',
            field=models.DateTimeField(default='2021-05-28 03:45:54.967731+00:00'),
        ),
        migrations.AlterField(
            model_name='bookedday',
            name='updated',
            field=models.DateTimeField(default='2021-05-28 03:45:54.967749+00:00'),
        ),
    ]
