# Generated by Django 2.2.5 on 2021-05-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20210528_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='created',
            field=models.DateTimeField(default='2021-05-28 03:47:19.658943+00:00'),
        ),
        migrations.AlterField(
            model_name='bookedday',
            name='updated',
            field=models.DateTimeField(default='2021-05-28 03:47:19.658962+00:00'),
        ),
    ]
