# Generated by Django 2.2.5 on 2021-05-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20210528_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='created',
            field=models.DateTimeField(default='2021-05-29 05:25:25.672804+00:00'),
        ),
        migrations.AlterField(
            model_name='bookedday',
            name='updated',
            field=models.DateTimeField(default='2021-05-29 05:25:25.672825+00:00'),
        ),
    ]
