# Generated by Django 2.2.5 on 2021-05-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20210529_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='created',
            field=models.DateTimeField(default='2021-05-29 08:59:30.973887+00:00'),
        ),
        migrations.AlterField(
            model_name='bookedday',
            name='updated',
            field=models.DateTimeField(default='2021-05-29 08:59:30.973918+00:00'),
        ),
    ]
