# Generated by Django 2.2.5 on 2021-04-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210419_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='houserules',
            new_name='house_rules',
        ),
    ]
