# Generated by Django 2.2.5 on 2021-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20210420_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reviews',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
