# Generated by Django 2.2.5 on 2021-04-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reviews',
        ),
    ]
