# Generated by Django 2.2.5 on 2021-05-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20210424_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='how many guests can the room accept?'),
        ),
    ]
